"""add_bank_id_and_created_at_to_payment

Revision ID: 6228ada94ffc
Revises: e5e681fe6348
Create Date: 2026-02-15 17:00:31.819476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6228ada94ffc'
down_revision: Union[str, None] = 'e5e681fe6348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('payments', sa.Column('bank_transaction_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'bank_transaction_id')
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###
